M48
; DRILL file KiCad 10.0.1 date 2026-05-12T02:02:41
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-12T02:02:41+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X21.0Y-66.075
X21.0Y-111.3
X109.7Y-111.3
X109.75Y-66.075
M30
