M48
; DRILL file KiCad 10.0.1 date 2026-05-12T01:23:48
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-12T01:23:48+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X116.68Y-107.464
X116.721Y-137.44
X171.619Y-137.342
X171.685Y-107.544
M30
