M48
; DRILL file KiCad 10.0.1 date 2026-04-29T21:41:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-29T21:41:56+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X29.687Y-167.802
X29.81Y-73.96
X164.31Y-73.9
X164.322Y-167.809
M30
