M48
; DRILL file KiCad 10.0.1 date 2026-04-26T23:42:25
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-26T23:42:25+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X59.5Y-65.0
X59.5Y-110.75
X129.25Y-65.0
X129.25Y-110.75
M30
